name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "wallet core release version"
        required: true
permissions:
  contents: write

jobs:
  upload_assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set version tag
        run: |
          if [ ${{ github.event.inputs.version }} ]; then
            echo "VER_NAME=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "no version"
          fi

      - name: Download from GPR
        run: |
          ./download.sh ${{ env.VER_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to release
        run: |
          gh release create ${{ env.VER_NAME }} --title ${{ env.VER_NAME }} --notes "Wallet Core Android" --draft
          cd ${{ env.VER_NAME }} && gh release upload ${{ env.VER_NAME }} ./*.aar ./*.jar ./*.sha1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Package.swift
        run: |
          mv ${{ env.VER_NAME }}/Package.swift .
          rm -rf ${{ env.VER_NAME }}
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git commit -a -m "Update Package.swift ${{ env.VER_NAME }}"
          git push
